# Development Environment Configuration

spring:
  # Database Configuration (H2 for development)
  datasource:
    url: jdbc:h2:mem:governance
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  
  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Logging Configuration
logging:
  level:
    com.bloominggrace.governance: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Exchange Rate Configuration
exchange:
  rate:
    default: 1000
    minimum-amount: 1000
    daily-limit: 100000

# Governance Configuration
governance:
  minimum-voting-power: 100
  default-voting-period-days: 7

# Solana Configuration (devnet for development)
solana:
  network: devnet
  rpc-url: https://api.devnet.solana.com
  wallet-path: /path/to/dev-wallet.json 