# Server Configuration
server:
  port: 8081
  servlet:
    context-path: /

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always

# Database Configuration (H2 for development)
spring:
  datasource:
    url: jdbc:h2:mem:governance;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  
  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

# Logging Configuration
logging:
  level:
    com.bloominggrace.governance: DEBUG
    org.springframework.security: DEBUG
    org.web3j: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

# Exchange Rate Configuration
exchange:
  rate:
    default: 1000
    minimum-amount: 1000
    daily-limit: 100000

# Governance Configuration
governance:
  minimum-voting-power: 100
  default-voting-period-days: 7

# Blockchain Configuration
blockchain:
  ethereum:
    # Sepolia 테스트넷 (무료)
    rpc-url: https://rpc.sepolia.org
    network-id: 11155111
    chain-id: 11155111
  solana:
    # Solana Devnet (무료)
    rpc-url: https://api.devnet.solana.com
    network-id: devnet

# Encryption Key
encryption:
  key: "12345678901234567890123456789012"

jwt:
  secret: your-secret-key-here-make-it-long-and-secure-in-production
  expiration: 86400000 # 24 hours in milliseconds
  issuer: "governance-platform" 